version: '3'

services:

  spring1:
    image: kerxd/spring-mysql-practica4

    container_name: spring1
    
    environment:
      - SERVER_PORT=8080

    networks:
      - practica4-mysql

    ports:
      - "82:80"

    depends_on:
      - mysqldb3
      
      
  spring2:
    image: kerxd/spring-mysql-practica4

    container_name: spring2
    
    environment:
      - SERVER_PORT=8081

    networks:
      - practica4-mysql

    ports:
      - "83:80"

    depends_on:
      - mysqldb3
      
      
  spring3:
    image: kerxd/spring-mysql-practica4

    container_name: spring3
    
    environment:
      - SERVER_PORT=8082

    networks:
      - practica4-mysql

    ports:
      - "84:80"

    depends_on:
      - mysqldb3
      
      
      
  ha-proxy:
    
    build: ./haproxy
    
    container_name: haproxy
    networks:
      - practica4-mysql
    
    ports:
      - "81:80"
      
      

  mysqldb3:
    image: mysql:8

    networks:
      - practica4-mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=practica4  
      
    volumes:
      - mysql_db:/var/lib/mysql
      
      
volumes:
  mysql_db:

networks:
  practica4-mysql:
